runtime: nodejs20

env: standard

service: gate-bot

automatic_scaling:
  min_instances: 0
  max_instances: 10

env_variables:
  NODE_ENV: "production"

handlers:
- url: /.*
  script: auto
  secure: always

liveness_check:
  path: "/health"
  initial_delay_sec: 30
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
