steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gate-bot:$COMMIT_SHA', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gate-bot:$COMMIT_SHA']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'gate-bot'
    - '--image'
    - 'gcr.io/$PROJECT_ID/gate-bot:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast3'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '3000'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '100'
    - '--max-instances'
    - '10'

images:
- 'gcr.io/$PROJECT_ID/gate-bot:$COMMIT_SHA'

timeout: '1200s'
