steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gate-bot:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    
  # Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/gate-bot:latest'
    
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gate-io-tradingview-new'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gate-bot:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--env-vars-file'
      - '.env.yaml'

images:
  - 'gcr.io/$PROJECT_ID/gate-bot:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1200s'
