
import { Language } from './types';

export const SYMBOLS = ["BTC_USDT", "ETH_USDT", "SOL_USDT", "BNB_USDT", "XRP_USDT"];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
    ko: {
        logo: "Gate.io 선물 거래",
        testnet: "테스트넷",
        mainnet: "메인넷",
        apiSettings: "API 설정",
        apiKey: "API 키",
        apiSecret: "API 시크릿",
        connect: "연결",
        connecting: "연결 중...",
        disconnect: "연결 해제",
        tradingSettings: "거래 설정",
        symbol: "심볼",
        investmentAmount: "투자금액 (USDT)",
        leverage: "레버리지",
        saveSettings: "설정 저장",
        currentPositions: "현재 포지션",
        noPositions: "열린 포지션이 없습니다",
        entryPrice: "진입가격",
        markPrice: "마크가격",
        pnl: "손익",
        pnlPercent: "손익률",
        size: "크기",
        margin: "증거금",
        closePosition: "포지션 종료",
        webhookSettings: "웹훅 설정",
        webhookDescription: "JSON 신호를 보내 자동으로 거래를 실행합니다",
        webhookUrl: "웹훅 URL",
        copy: "복사",
        copied: "복사됨!",
        startWebhook: "서버 시작",
        stopWebhook: "서버 중지",
        webhookLogs: "웹훅 로그",
        connected: "연결됨",
        disconnected: "연결 안됨",
        settingsSaved: "설정이 저장되었습니다",
        webhookStarted: "웹훅 서버가 시작되었습니다",
        webhookStopped: "웹훅 서버가 중지되었습니다",
        urlCopied: "URL이 복사되었습니다",
        connectionSuccess: "API 연결 성공",
        connectionFailed: "API 연결 실패",
        positionOpened: "포지션 진입",
        positionClosed: "포지션 종료",
        invalidCredentials: "잘못된 API 자격 증명",
        enterApiCredentials: "API 자격 증명을 입력하세요",
        long: "롱",
        short: "숏",
        noLogs: "로그가 없습니다"
    },
    en: {
        logo: "Gate.io Futures Trading",
        testnet: "Testnet",
        mainnet: "Mainnet",
        apiSettings: "API Settings",
        apiKey: "API Key",
        apiSecret: "API Secret",
        connect: "Connect",
        connecting: "Connecting...",
        disconnect: "Disconnect",
        tradingSettings: "Trading Settings",
        symbol: "Symbol",
        investmentAmount: "Investment Amount (USDT)",
        leverage: "Leverage",
        saveSettings: "Save Settings",
        currentPositions: "Current Positions",
        noPositions: "No open positions",
        entryPrice: "Entry Price",
        markPrice: "Mark Price",
        pnl: "PnL",
        pnlPercent: "PnL %",
        size: "Size",
        margin: "Margin",
        closePosition: "Close Position",
        webhookSettings: "Webhook Settings",
        webhookDescription: "Send JSON signals to execute trades automatically",
        webhookUrl: "Webhook URL",
        copy: "Copy",
        copied: "Copied!",
        startWebhook: "Start Server",
        stopWebhook: "Stop Server",
        webhookLogs: "Webhook Logs",
        connected: "Connected",
        disconnected: "Disconnected",
        settingsSaved: "Settings saved",
        webhookStarted: "Webhook server started",
        webhookStopped: "Webhook server stopped",
        urlCopied: "URL copied",
        connectionSuccess: "API connection successful",
        connectionFailed: "API connection failed",
        positionOpened: "Position opened",
        positionClosed: "Position closed",
        invalidCredentials: "Invalid API credentials",
        enterApiCredentials: "Please enter API credentials",
        long: "LONG",
        short: "SHORT",
        noLogs: "No logs yet"
    },
    ja: {
        logo: "Gate.io 先物取引",
        testnet: "テストネット",
        mainnet: "メインネット",
        apiSettings: "API設定",
        apiKey: "APIキー",
        apiSecret: "APIシークレット",
        connect: "接続",
        connecting: "接続中...",
        disconnect: "切断",
        tradingSettings: "取引設定",
        symbol: "シンボル",
        investmentAmount: "投資額 (USDT)",
        leverage: "レバレッジ",
        saveSettings: "設定を保存",
        currentPositions: "現在のポジション",
        noPositions: "オープンポジションなし",
        entryPrice: "参入価格",
        markPrice: "マーク価格",
        pnl: "損益",
        pnlPercent: "損益率",
        size: "サイズ",
        margin: "証拠金",
        closePosition: "ポジションを閉じる",
        webhookSettings: "Webhook設定",
        webhookDescription: "JSON信号を送信して自動的に取引を実行します",
        webhookUrl: "Webhook URL",
        copy: "コピー",
        copied: "コピーしました！",
        startWebhook: "サーバー開始",
        stopWebhook: "サーバー停止",
        webhookLogs: "Webhookログ",
        connected: "接続済み",
        disconnected: "未接続",
        settingsSaved: "設定が保存されました",
        webhookStarted: "Webhookサーバーが開始されました",
        webhookStopped: "Webhookサーバーが停止されました",
        urlCopied: "URLがコピーされました",
        connectionSuccess: "API接続成功",
        connectionFailed: "API接続失敗",
        positionOpened: "ポジション開始",
        positionClosed: "ポジション終了",
        invalidCredentials: "無効なAPI認証情報",
        enterApiCredentials: "API認証情報を入力してください",
        long: "ロング",
        short: "ショート",
        noLogs: "まだログはありません"
    }
};
