version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gate-bot:latest
    container_name: gate-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - gate-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  gate-network:
    driver: bridge

volumes:
  logs:
  data:
